# Welcome to Jekyll!

# Website settings
title: Hilmi Coşkun
description: Hilmi Coşkun'un kişisel sayfası.

# url: 'http://hilmicoskun.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  first_name: Hilmi
  last_name: Coşkun
  email: mail@hilmicoskun.com
  # twitter_username:
  facebook_username: hilmi.coskun.549
  github_username:  hilmicoskun
  # linkedin_username:
  head_img: 'images/profile.jpg'

# blog img path
img_path: '/static/img/blog'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects
projects:
  - saplatform:
    name: 'Saplatform'
    github_path: '/Jack614/saplatform'
    img: 'static/img/landing/saplatform.png'
    description: 'Test'


# blog index
index:
  home: 'Home'
  embedded: 'Embedded'
  electronics: 'Electronics'
  life: 'Life'

# donate
# donate:
#   wechat: 'static/img/pay/wechat.png'
#   alipay: 'static/img/pay/alipay.png'

# comment
disqus:
  name: hilmicoskun
  public_key:

# google analytics
ga:
  id: ###

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /blog/:year/:title/
